# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'MTBBarcodeScannerExample' do

pod 'Firebase/Core'
pod 'Firebase/Database'

end

target 'MTBBarcodeScanner' do

end

